import React from 'react';
import { useNavigate } from 'react-router-dom';
import './LegalPages.css';

const TermsOfUse = () => {
    const navigate = useNavigate();

    return (
        <div className="legal-page-container">
            <div className="legal-content">
                <h1>Terms of Use</h1>
                <p className="last-updated">Last Updated: December 2025</p>

                <div className="legal-sections">
                    <section>
                        <h2>1. Introduction</h2>
                        <p>Welcome to Viridi Cervus. This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                        <p>Your use of the website and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the website including the applicable policies which are incorporated herein by way of reference.</p>
                    </section>

                    <section>
                        <h2>2. Membership Eligibility</h2>
                        <p>Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website.</p>
                    </section>

                    <section>
                        <h2>3. Your Account and Registration Obligations</h2>
                        <p>If you use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete, We have the right to indefinitely suspend or terminate or block access of your membership on the Website.</p>
                    </section>

                    <section>
                        <h2>4. Communications</h2>
                        <p>When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required.</p>
                    </section>

                    <section>
                        <h2>5. Charges</h2>
                        <p>Membership on the Website is free for buyers. Viridi Cervus does not charge any fee for browsing and buying on the Website. Viridi Cervus reserves the right to change its Fee Policy from time to time.</p>
                    </section>
                    <section>
                        <h2>6. Limitation of Liability</h2>
                        <p>In no event shall Viridi Cervus be liable for any special, incidental, indirect or consequential damages of any kind in connection with these terms of use, even if user has been informed in advance of the possibility of such damages.</p>
                    </section>

                    <button className="continue-btn" onClick={() => window.close()}>Continue</button>
                </div>
            </div>
        </div>
    );
};

export default TermsOfUse;
